# Generated by Django 5.2.14 on 2026-06-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
